name: suntigen
favicon: null
layout_spectrum: 0.5268006399273872
typography_spectrum: 0.18444565823301673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.471631218213588
  lightness: 0.33503819024190307
  saturation: 0.851035115076229
  rhythmicContrast: 0.13498900784179568
purpose: []
