favicon: null
name: suntigen
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8510351
  brandStrength: 0.811493
  lightness: 0.1122449
  brandColors:
    - '#FFFFFF'
    - '#020000'
    - '#D8A25C'
    - '#392001'
    - '#FCCF9A'
  rhythmicContrast: 0.7910848
typography_spectrum: 0
layout_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
